### ISSUE TITLE
Duplicate ClientLobbyIpcType in CN_2023.09.06/Ipcs_cn.cs

### ISSUE THREAD

**Issue by StarHeartHunt** [gamous/FFXIVNetworkOpcodes#19]
https://github.com/gamous/FFXIVNetworkOpcodes/blob/12e371c1ee692ba3623014092e25dc78e62bbf95/output/CN_2023.09.06/Ipcs_cn.cs#L9

https://github.com/gamous/FFXIVNetworkOpcodes/blob/12e371c1ee692ba3623014092e25dc78e62bbf95/output/CN_2023.09.06/Ipcs_cn.cs#L145

**Comment by gamous** [comment]
fixed
